# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f90c0dd3817b27cbf74a27b63949696b66d6db4b11bf135d9a9538ee6363b46b78a8e5fedd0e2f3a38d8973dd9f14e312522c7e25d363d7ff82233c603304202

test:
  secret_key_base: 20fbf1ec990982507845892c69cb84a9f644c419663023482e07c1e52c0701b0bac98e78a36b6cd8d1fb34ffd55125663c5e3d12ca4eaf05da71775b5deeba98

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
